apiVersion: v1
kind: Namespace
metadata:
  name: k8s-monitoring

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-monitoring-dashboard
  namespace: k8s-monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-monitoring-dashboard
rules:
- apiGroups: [""]
  resources: ["nodes", "namespaces", "pods", "services", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-monitoring-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-monitoring-dashboard
subjects:
- kind: ServiceAccount
  name: k8s-monitoring-dashboard
  namespace: k8s-monitoring

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-monitoring-dashboard
  namespace: k8s-monitoring
  labels:
    app: k8s-monitoring-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-monitoring-dashboard
  template:
    metadata:
      labels:
        app: k8s-monitoring-dashboard
    spec:
      serviceAccountName: k8s-monitoring-dashboard
      containers:
      - name: k8s-monitoring-dashboard
        image: k8s-monitoring-dashboard:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-monitoring-dashboard
  namespace: k8s-monitoring
spec:
  selector:
    app: k8s-monitoring-dashboard
  ports:
  - port: 8888
    targetPort: 8888
  type: ClusterIP
